function [params, species] = nfkbInitialize()
% This file is automatically generated by updateModel.m from the NFkB whole-cell spreadsheet
% Model URL: multi-stimulus NFkB.xlsx


% PARAMETERS
params(1,1) = 1; % induced IKK activation (general)
params(2,1) = 2e-05; % basal IKK activation
params(3,1) = 2; % IKK inhibition (IKK cycling)
params(4,1) = 18; % IKK renewal (IKK cycling)
params(5,1) = 2e-06; % basal IkBa mRNA synthesis
params(6,1) = 6e-05; % induced IkBa mRNA synthesis
params(6,2) = 2.938; % Hill coefficient for mRNA syn
params(6,3) = 0.1775; % EC50 for mRNA syn
params(6,4) = 14; % mRNA transcription/processing/maturation delay
params(7,1) = 0.0577623; % IkBa mRNA degradation
params(8,1) = 30; % IkBa mRNA translation
params(8,2) = 1; % Translation/folding delay
params(9,1) = 0.0225; % nuclear import of IkBa
params(9,2) = 3.5; % Volume scale: cytoplasmic/nuclear volume
params(10,1) = 0.6; % nuclear import of RelA
params(10,2) = 3.5; % Volume scale: cytoplasmic/nuclear volume
params(11,1) = 0.1575; % nuclear export of IkBa
params(11,2) = 0.285714; % Volume scale: nuclear/cytoplasmic volume
params(12,1) = 0.042; % nuclear export of RelA
params(12,2) = 0.285714; % Volume scale: nuclear/cytoplasmic volume
params(13,1) = 0; % nuclear import of IkBa-RelA
params(13,2) = 3.5; % Volume scale: cytoplasmic/nuclear volume
params(14,1) = 0.828; % nuclear export of IkBa-RelA
params(14,2) = 0.285714; % Volume scale: cytoplasmic/nuclear volume
params(15,1) = 0.0770164; % degradation of IkBa
params(16,1) = 0.0770164; % degradation of IkBa (nuc)
params(17,1) = 200; % IkBa-RelA association
params(18,1) = 200; % IkBa-RelA association (nuc)
params(19,1) = 0.008; % IkBa-RelA dissociation
params(20,1) = 0.008; % IkBa-RelA dissociation (nuc)
params(21,1) = 190; % IKK-IkBa-RelA association
params(22,1) = 190; % IKK-IkBa association
params(23,1) = 38; % IKK-IkBa-RelA dissociation
params(24,1) = 38; % IKK-IkBa dissociation
params(25,1) = 2; % Phosphorylation/degradation of complexed IkBa
params(26,1) = 2; % Phosphorylation/degradation of IkBa
params(27,1) = 4e-08; % basal IkBe mRNA synthesis
params(28,1) = 1.5e-06; % induced IkBe mRNA synthesis from cRel
params(28,2) = 2.938; % Hill coefficient for mRNA syn
params(28,3) = 0.1775; % EC50 for mRNA syn
params(28,4) = 45; % mRNA transcription/processing/maturation delay
params(29,1) = 0.00506409; % IkBe mRNA degradation
params(30,1) = 30; % IkBe mRNA translation
params(30,2) = 1; % Translation/folding delay
params(31,1) = 0.016875; % nuclear import of IkBe
params(31,2) = 3.5; % Volume scale: cytoplasmic/nuclear volume
params(32,1) = 0.6; % nuclear import of cRel:p50
params(32,2) = 3.5; % Volume scale: cytoplasmic/nuclear volume
params(33,1) = 0.1575; % nuclear export of IkBe
params(33,2) = 0.285714; % Volume scale: nuclear/cytoplasmic volume
params(34,1) = 0.042; % nuclear export of cRel:p50
params(34,2) = 0.285714; % Volume scale: nuclear/cytoplasmic volume
params(35,1) = 0; % nuclear import of IkBe-NFkB
params(35,2) = 3.5; % Volume scale: cytoplasmic/nuclear volume
params(36,1) = 0.414; % nuclear export of IkBe-NFkB
params(36,2) = 0.285714; % Volume scale: cytoplasmic/nuclear volume
params(37,1) = 0.00741282; % degradation of IkBe
params(38,1) = 0.00741282; % degradation of IkBe (nuc)
params(39,1) = 55.9301; % IkBe-cRel association
params(40,1) = 55.9301; % IkBe-cRel association (nuc)
params(41,1) = 3.576e-05; % IkBe-cRel dissociation
params(42,1) = 3.576e-05; % IkBe-cRel dissociation (nuc)
params(43,1) = 46.1429; % IKK-IkBe-cRel association
params(44,1) = 46.1429; % IKK-IkBe association
params(45,1) = 38; % IKK-IkBe-cRel dissociation
params(46,1) = 38; % IKK-IkBe dissociation
params(47,1) = 1.33; % Phosphorylation/degradation of complexed IkBe
params(48,1) = 1.33; % Phosphorylation/degradation of IkBe
params(49,1) = 3e-07; % induced IkBe mRNA synthesis from RelA
params(49,2) = 2.938; % Hill coefficient for mRNA syn
params(49,3) = 0.1775; % EC50 for mRNA syn
params(49,4) = 45; % mRNA transcription/processing/maturation delay
params(50,1) = 0; % nuclear import of IkBa-NFkB
params(50,2) = 3.5; % Volume scale: cytoplasmic/nuclear volume
params(51,1) = 0; % nuclear import of IkBe-NFkB
params(51,2) = 3.5; % Volume scale: cytoplasmic/nuclear volume
params(52,1) = 0.828; % nuclear export of IkBa-NFkB
params(52,2) = 0.285714; % Volume scale: cytoplasmic/nuclear volume
params(53,1) = 0.414; % nuclear export of IkBe-NFkB
params(53,2) = 0.285714; % Volume scale: cytoplasmic/nuclear volume
params(54,1) = 125.094; % IkBa-cRel association
params(55,1) = 55.9301; % IkBe-RelA association
params(56,1) = 125.094; % IkBa-cRel association (nuc)
params(57,1) = 55.9301; % IkBe-RelA association (nuc)
params(58,1) = 0.064; % IkBa-cRel dissociation
params(59,1) = 0.08; % IkBe-RelA dissociation
params(60,1) = 0.064; % IkBa-cRel dissociation (nuc)
params(61,1) = 0.08; % IkBe-RelA dissociation (nuc)
params(62,1) = 190; % IKK-IkBa-cRel association
params(63,1) = 46.1429; % IKK-IkBe-RelA association
params(64,1) = 38; % IKK-IkBa-cRel dissociation
params(65,1) = 38; % IKK-IkBe-RelA dissociation
params(66,1) = 2; % Phosphorylation/degradation of complexed IkBa
params(67,1) = 1.33; % Phosphorylation/degradation of complexed IkBe
params(68,1) = 3; % CD14-LPS association
params(68,2) = 0.001; % Scale for external (media) vs. internal (cellular) volumes
params(69,1) = 0.07; % CD14-LPS dissociation
params(69,2) = 0.001; % Scale for external (media) vs. internal (cellular) volumes
params(70,1) = 0.00112; % CD14 synthesis
params(71,1) = 0.000878; % CD14 degradation
params(72,1) = 5.543; % Assocation of LPS and CD14 in plasma membrane
params(73,1) = 0.0277; % Disassociation of TLR4LPS in the plamsa membrane
params(74,1) = 5.543; % Assocation of LPS and CD14 in the endosome
params(75,1) = 0.0277; % Disassociation of TLR4LPS in the endosome
params(76,1) = 5.25e-05; % Synthesis rate of TLR4
params(77,1) = 0.065681; % Induced endocytosis of CD14
params(78,1) = 0.04; % Recycling of CD14
params(79,1) = 0.028028; % Constitutive endocytosis of TLR4
params(80,1) = 5; % Recycling of TLR4
params(81,1) = 0.065681; % Induced endocytosis of activated CD14-TLR4
params(82,1) = 0.04; % Recycling of CD14-TLR4
params(83,1) = 0.07; % Degradation of CD14-LPS
params(84,1) = 0.0653; % Degradation of TLR4
params(85,1) = 0.012; % Degradation of activated TLR4-LPS
params(86,1) = 150; % Activation of MyD88
params(86,2) = 3; % Hill coefficient for MyD88 activation
params(86,3) = 0.012448; % EC50 for MyD88 activation
params(87,1) = 2600; % Deactivation of MyD88
params(88,1) = 6; % Activation of TRIF
params(89,1) = 0.04; % Deactivation of TRIF
params(90,1) = 30; % Activation of TRAF6 by MyD88
params(91,1) = 0.4; % Activation of TRAF6 by TRIF
params(92,1) = 0.125; % Deactivation of TRAF6
params(93,1) = 0.105; % Activation of TAK1 by TRAF6
params(94,1) = 0.0058; % TNF degradation
params(95,1) = 8.224e-06; % TNFR synthesis
params(96,1) = 0.02384; % TNFR degradation
params(97,1) = 1100; % Capture of TNF
params(97,2) = 0.001; % Scale for external (media) vs. internal (cellular) volumes
params(98,1) = 0.021; % Release of TNF
params(98,2) = 0.001; % Scale for external (media) vs. internal (cellular) volumes
params(99,1) = 0.125; % Internalization/degradation of complexed TNFR
params(100,1) = 34.08; % Association of TRAF2/RIP1 with receptor trimer
params(101,1) = 0.03812; % Dissociation of TRAF2/RIP1 with receptor trimer
params(102,1) = 0.125; % Internalization/degradation of complexed TNFR
params(103,1) = 1.3393; % Activation of complexed TNFR
params(104,1) = 320.3; % Inactivation of complexed TNFR
params(105,1) = 0.125; % Internalization/degradation of complexed TNFR
params(106,1) = 1889; % Activation of TAK1 by C1
params(107,1) = 0.5188; % Inactivation of TAK1
params(108,1) = 18.79; % Activation of IKK by TAK1
params(108,2) = 2; % Hill coefficient for IKK activation
params(108,3) = 0.001116; % EC50 for mRNA syn
params(109,1) = 1.25e-06; % TLR1/2 synthesis
params(110,1) = 0.0004; % TLR1/2 degradation
params(111,1) = 1; % Association of CD14 and lipoprotein
params(111,2) = 0.001; % Scale for external (media) vs. internal (cellular) volumes
params(112,1) = 1.8; % Dissociation of CD14/lipoprotein
params(112,2) = 0.001; % Scale for external (media) vs. internal (cellular) volumes
params(113,1) = 5.543; % CD14-P3CSK and TLR2 association
params(114,1) = 0.07; % Degradation of CD14-P3CSK
params(115,1) = 0.02; % CD14-P3CSK and TLR2 dissociation
params(116,1) = 0.001; % Degradation of ligand/receptor
params(117,1) = 150; % Activation of MyD88
params(117,2) = 3; % Hill coefficient for MyD88 activation
params(117,3) = 0.004; % EC50 for MyD88 activation
params(118,1) = 3e-06; % TLR3 synthesis
params(119,1) = 0.001; % TLR3 degradation
params(120,1) = 0.04; % Poly(I:C) internalization
params(120,2) = 0.03; % EC50 for poly(I:C) internalization
params(120,3) = 1; % Hill coefficient for poly(I:C) internalization
params(120,4) = 0.001; % NaN
params(121,1) = 0.04; % Poly(I:C) deinternalization
params(121,2) = 0.001; % Poly(I:C) release
params(122,1) = 0.5; % NaN
params(123,1) = 0.025; % NaN
params(124,1) = 0.001; % Bound poly(I:C)-TLR3 degradation
params(125,1) = 20; %  Activation of TRIF by bound TLR3
params(126,1) = 2e-06; % TLR9 synthesis
params(127,1) = 0.0004; % TLR9 degradation
params(128,1) = 0.0004; % TLR9 degradation (N terminus fragment)
params(129,1) = 0.0022; % CpG internalization
params(129,2) = 0.5; % EC50 for CpG internalization
params(129,3) = 1; % Hill coefficient for CpG internalization
params(129,4) = 0.001; % NaN
params(130,1) = 0.028; % CpG exchange from endosome
params(130,2) = 0.001; % NaN
params(131,1) = 3; % Ligand-receptor association
params(132,1) = 0.5; % Ligand-receptor dissociation
params(133,1) = 0.03; % Mediated degrdadation of bound TLR9
params(134,1) = 0.0016; % Bound CpG-TLR9 degradation
params(135,1) = 200; % Activation of MyD88
params(135,2) = 3; % Hill coefficient for MyD88 activation
params(135,3) = 0.0032; % EC50 for MyD88 activation
params(136,1) = 2e-06; % TLR5 receptor synthesis
params(137,1) = 0.0005; % TLR5 receptor degradation
params(138,1) = 3; % Ligand-receptor association
params(138,2) = 0.001; % Scale for external (media) vs. internal (cellular) volumes
params(139,1) = 0.04; % Ligand-receptor dissociation
params(139,2) = 0.001; % Scale for external (media) vs. internal (cellular) volumes
params(140,1) = 0.015; % Ligand-receptor complex degradation
params(141,1) = 150; % Activation of MyD88
params(141,2) = 3; % Hill coefficient for MyD88 activation
params(141,3) = 0.0015; % EC50 for MyD88 activation
params(142,1) = 1e-06; % TLR7/8 synthesis
params(143,1) = 0.0007; % TLR7 degradation
params(144,1) = 0.07; % R848 internalization
params(144,2) = 0.03; % EC50 for R848 internalization
params(144,3) = 1; % Hill coefficient for R848 internalization
params(144,4) = 0.001; % NaN
params(145,1) = 0.07; % R848 exchange from endosome
params(145,2) = 0.001; % NaN
params(146,1) = 1; % Ligand-receptor association
params(147,1) = 0.64; % Ligand-receptor dissociation
params(148,1) = 0.0015; % Bound R848-TLR7 degradation
params(149,1) = 150; % Activation of MyD88
params(149,2) = 3; % Hill coefficient for MyD88 activation
params(149,3) = 0.002; % EC50 for MyD88 activation


% SPECIES
species.NAMES = {...
'stim' ...1
'IkBa' ...2
'IkBan' ...3
'IkBe' ...4
'IkBen' ...5
'IkBaRelA' ...6
'IkBaRelAn' ...7
'IkBacRel' ...8
'IkBacReln' ...9
'IkBeRelA' ...10
'IkBeRelAn' ...11
'IkBecRel' ...12
'IkBecReln' ...13
'IkBat' ...14
'IkBet' ...15
'IKKIkBaRelA' ...16
'IKKIkBacRel' ...17
'IKKIkBa' ...18
'IKKIkBeRelA' ...19
'IKKIkBecRel' ...20
'IKKIkBe' ...21
'cRel' ...22
'cReln' ...23
'RelA' ...24
'RelAn' ...25
'IKK_off' ...26
'IKK' ...27
'IKK_i' ...28
'LPS' ...29
'CD14' ...30
'CD14LPS' ...31
'CD14LPSen' ...32
'TLR4' ...33
'TLR4en' ...34
'TLR4LPS' ...35
'TLR4LPSen' ...36
'MyD88_off' ...37
'MyD88' ...38
'TRIF_off' ...39
'TRIF' ...40
'TRAF6_off' ...41
'TRAF6' ...42
'TNF' ...43
'TNFR' ...44
'TNFR_TNF' ...45
'TTR' ...46
'C1_off' ...47
'C1' ...48
'TAK1_off' ...49
'TAK1' ...50
'Pam3CSK' ...51
'TLR2' ...52
'CD14_P3CSK' ...53
'TLR2_P3CSK' ...54
'polyIC' ...55
'polyIC_en' ...56
'TLR3' ...57
'TLR3_polyIC' ...58
'CpG' ...59
'CpG_en' ...60
'TLR9' ...61
'TLR9_CpG' ...62
'TLR9_N' ...63
'FLA' ...64
'TLR5' ...65
'TLR5_FLA' ...66
'R848' ...67
'R848_en' ...68
'TLR7' ...69
'TLR7_R848' ...70
};